# Generated by Django 5.1.7 on 2025-04-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('date_of_birth', models.DateField()),
                ('bodyweight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('snatch_attempt_1', models.IntegerField(blank=True)),
                ('snatch_attempt_1_make', models.BooleanField(blank=True)),
                ('snatch_attempt_2', models.IntegerField(blank=True)),
                ('snatch_attempt_2_make', models.BooleanField(blank=True)),
                ('snatch_attempt_3', models.IntegerField(blank=True)),
                ('snatch_attempt_3_make', models.BooleanField(blank=True)),
                ('cnj_attempt_1', models.IntegerField(blank=True)),
                ('cnj_attempt_1_make', models.BooleanField(blank=True)),
                ('cnj_attempt_2', models.IntegerField(blank=True)),
                ('cnj_attempt_2_make', models.BooleanField(blank=True)),
                ('cnj_attempt_3', models.IntegerField(blank=True)),
                ('cnj_attempt_3_make', models.BooleanField(blank=True)),
            ],
        ),
    ]
