# Generated by Django 5.1.7 on 2025-04-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='cnj_attempt_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='cnj_attempt_1_make',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='cnj_attempt_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='cnj_attempt_2_make',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='cnj_attempt_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='cnj_attempt_3_make',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='snatch_attempt_1_make',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='snatch_attempt_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='snatch_attempt_2_make',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='snatch_attempt_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='snatch_attempt_3_make',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
