# Generated by Django 5.1.7 on 2025-04-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_alter_competitor_cnj_attempt_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='cnj_attempt_1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competitor',
            name='snatch_attempt_1',
            field=models.IntegerField(),
        ),
    ]
