# Generated by Django 5.1.7 on 2025-04-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_alter_competitor_cnj_attempt_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
